### ISSUE TITLE
symbolic link in val_videodatainfo.json

### ISSUE THREAD

**Issue by chihyaoma** [mynlp/cst_captioning#1]
Hi

Thanks for sharing this amazing git repo for your paper. 

Regarding the symbolic link in **val_videodatainfo.json**

It seems that there is an issue when viewing/downloading from your google drive for this particular file. 

This issue is preventing me from correctly generating metadata using the command below. 
> make pre_process

Could you kindly double-check the file? Thanks!

**Comment by chihyaoma** [comment]
Remove the downloaded file and manually create a symbolic link seems to solve the problem.

> ln -s train_videodatainfo.json val_videodatainfo.json

**Comment by plsang** [comment]
Yes, that should solve the problem.  Thanks for reporting the issue!
