### ISSUE TITLE
No such file or directory: 'data/output/metadata/msrvtt_train_ciderdf.pkl.p'

### ISSUE THREAD

**Issue by chihyaoma** [mynlp/cst_captioning#2]
Hi, 

I was just trying to run with your default setting:

**Train CST_GT_None/WXE model**

> make train GID=0 EXP_NAME=WXE FEATS="resnet c3d mfcc category" USE_RL=1 USE_CST=1 USE_MIXER=0 SCB_CAPTIONS=0 LOGLEVEL=DEBUG MAX_EPOCHS=50

Here is the error I got: 
```
Traceback (most recent call last):
  File "train.py", line 529, in <module>
    rl_criterion=rl_criterion)
  File "train.py", line 118, in train
    'CIDEr': CiderD(df=opt.train_cached_tokens),
  File "cider/pyciderevalcap/ciderD/ciderD.py", line 25, in __init__
    self.cider_scorer = CiderScorer(n=self._n, df_mode=self._df)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 69, in __init__
    pkl_file = pickle.load(open(os.path.join('data', df_mode + '.p'),'r'))
IOError: [Errno 2] No such file or directory: 'data/output/metadata/msrvtt_train_ciderdf.pkl.p'
```

There seems to be an issue with the way how we load pickle file within CIDer. Making following change solved the problem. 

In "cider/pyciderevalcap/ciderD/ciderD_scorer.py"
```python
# Line #69 is wrong:
# pkl_file = pickle.load(open(os.path.join('data', df_mode + '.p'),'r'))

# It should be changed to:
pkl_file = pickle.load(open(os.path.join(df_mode),'r'))
```

**Comment by plsang** [comment]
Thanks for reporting this issue.  I have updated the link to my modified CIDEr code, which solved this issue.
